### ISSUE TITLE
Require two Heros to CR every change

### ISSUE THREAD

**Issue by ZainRizvi** [enomic/enomic#30]
Every change should have a CR by at least one other hero as a safety check so that the guy making the change doesn't accidentally bork the server (like I did :P)

**Comment by arnoldblake** [comment]
I agree

**Comment by ZainRizvi** [comment]
It's also a good way to prevent villainy 

Sent from my Windows Phone

-----Original Message-----

**Comment by drewry** [comment]
:+1:

**Comment by enomic** [comment]
+1, lets do this

**Comment by arnoldblake** [comment]
Which events is the github webhook sending? I'm guessing its only the 'pull request review comment' event.

**Comment by cinderblock** [comment]
I wrote a thing that does this. #40
