### ISSUE TITLE
Development fork

### ISSUE THREAD

**Issue by arnoldblake** [enomic/enomic#34]
I have a development fork running. If anyone wants to use it your more than welcome. I will be using it to test changes. You can submit your pull requests to the development branch.
https://github.com/arnoldblake/enomic

**Comment by cinderblock** [comment]
Nice! I was thinking of implementing travis or something. I might test my new PR on your's first.

**Comment by logannc** [comment]
Wouldn't it be more in the spirit of things to just have a development branch on the main repo?
